/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.transporteshirata.GUI;

import com.mycompany.transporteshirata.Datos.EquipoOficinaDao;
import com.mycompany.transporteshirata.Datos.MantenimientoEquipoDao;
import com.mycompany.transporteshirata.Datos.PiezaInventarioDao;
import com.mycompany.transporteshirata.Logica.EquipoOficina;
import com.mycompany.transporteshirata.Logica.MantenimientoEquipoOficina;
import com.mycompany.transporteshirata.Logica.PiezaInventario;
import java.time.LocalDate;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nicolas
 */
public class GuiMantenimientoEquipos extends javax.swing.JInternalFrame {
    public static GuiMantenimientoEquipos instancia = null;
    EquipoOficinaDao ed = new EquipoOficinaDao();
    MantenimientoEquipoDao mantDao = new MantenimientoEquipoDao();
    PiezaInventarioDao piezaDao = new PiezaInventarioDao();

    /**
     * Creates new form GuiMantenimientoEquipos
     */
    public GuiMantenimientoEquipos() {
        initComponents();
        instancia = this;                 // asigno la instancia actual
        cargarComboEquipos();             // llena el combo con nombres
        cargarComboPiezas();
        cargarTablaMantenimientos();
        cambiarAModoNuevo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmb_tipomanequipo = new javax.swing.JComboBox<>();
        cmb_equipos = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        txt_fechaequipo = new javax.swing.JTextField();
        txt_descripcionman = new javax.swing.JTextField();
        txt_observaciones = new javax.swing.JTextField();
        bt_registrar = new javax.swing.JButton();
        bt_cerrar = new javax.swing.JButton();
        bt_editar = new javax.swing.JButton();
        bt_cancelar = new javax.swing.JButton();
        bt_eliminar = new javax.swing.JButton();
        cmb_estado = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmb_piezas = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txt_cantidadpieza = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        bt_refrescar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel1.setText("ID");

        jLabel2.setText("Fecha");

        jLabel3.setText("Tipo de Mantenimiento");

        jLabel4.setText("Descripcion de Mantenimiento");

        jLabel5.setText("Observaciones");

        jLabel6.setText("Equipo");

        cmb_tipomanequipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Preventivo", "Correctivo" }));

        cmb_equipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_equipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_equiposActionPerformed(evt);
            }
        });

        bt_registrar.setText("Guardar");
        bt_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_registrarActionPerformed(evt);
            }
        });

        bt_cerrar.setText("Salir");
        bt_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cerrarActionPerformed(evt);
            }
        });

        bt_editar.setText("Editar");
        bt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarActionPerformed(evt);
            }
        });

        bt_cancelar.setText("Cancelar");
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        bt_eliminar.setText("Eliminar");
        bt_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminarActionPerformed(evt);
            }
        });

        cmb_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "Mantencion", "En Revision", "Fuera de Linea" }));
        cmb_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_estadoActionPerformed(evt);
            }
        });

        jLabel7.setText("Estado");

        jLabel9.setText("Repuesto usado");

        jLabel10.setText("Cantidad repuesto");

        jLabel8.setText("Buscar por ID:");

        bt_refrescar.setText("Buscar");
        bt_refrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_refrescarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_eliminar)
                .addGap(118, 118, 118))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(151, 151, 151)
                                .addComponent(txt_fechaequipo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bt_cerrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bt_cancelar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(147, 147, 147)
                                        .addComponent(cmb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(88, 88, 88)
                                        .addComponent(cmb_piezas, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(69, 69, 69)
                                        .addComponent(txt_cantidadpieza, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(bt_registrar)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bt_refrescar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(bt_editar))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_descripcionman)
                                        .addComponent(txt_observaciones)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel6))
                                    .addGap(57, 57, 57)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cmb_tipomanequipo, 0, 121, Short.MAX_VALUE)
                                        .addComponent(cmb_equipos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txt_fechaequipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmb_tipomanequipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_descripcionman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_observaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmb_equipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmb_piezas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_cantidadpieza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_registrar)
                    .addComponent(bt_editar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_eliminar)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_refrescar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_cerrar)
                    .addComponent(bt_cancelar))
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1145, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_registrarActionPerformed
        if (txt_fechaequipo.getText().trim().isEmpty() ||
        txt_descripcionman.getText().trim().isEmpty() ||
        cmb_tipomanequipo.getSelectedItem() == null ||
        cmb_equipos.getSelectedItem() == null ||
        cmb_estado.getSelectedItem() == null) {
        
        JOptionPane.showMessageDialog(this, "⚠️ Debes completar todos los campos antes de guardar");
        return;
    }
        int fila = jTable1.getSelectedRow();

        if (cmb_equipos.getItemCount() == 0 || cmb_equipos.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un equipo en el combo.");
            return;
        }

        try {
            MantenimientoEquipoOficina m = new MantenimientoEquipoOficina();

            if (txt_fechaequipo.getText().trim().isEmpty()) {
                m.setFecha(LocalDate.now());
            } else {
                try {
                    m.setFecha(LocalDate.parse(txt_fechaequipo.getText().trim()));
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Use YYYY-MM-DD.");
                    return;
                }
            }

            m.setTipo(cmb_tipomanequipo.getSelectedItem().toString());
            m.setDescripcion(txt_descripcionman.getText());
            m.setObservaciones(txt_observaciones.getText());
            PiezaInventario piezaSeleccionada = (PiezaInventario) cmb_piezas.getSelectedItem();
            if (piezaSeleccionada != null && piezaSeleccionada.getIdPieza() > 0) {
                if (txt_cantidadpieza.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Ingrese la cantidad de repuestos usados.");
                    return;
                }
                int cantidadUsada = Integer.parseInt(txt_cantidadpieza.getText().trim());
                if (cantidadUsada <= 0) {
                    JOptionPane.showMessageDialog(this, "La cantidad de repuestos debe ser mayor a 0.");
                    return;
                }
                m.setPiezaUsada(piezaSeleccionada);
                m.setCantidadPiezaUsada(cantidadUsada);
            }

            // Equipo: buscar por nombre
            EquipoOficina equipoSeleccionado = null;
            String nombreSel = (String) cmb_equipos.getSelectedItem();
            if (nombreSel != null) {
                List<EquipoOficina> lista = ed.listarEquipos();
                if (lista != null) {
                    for (EquipoOficina e : lista) {
                        if (nombreSel.equals(e.getNombre())) {
                            equipoSeleccionado = e;
                            break;
                        }
                    }
                }
            }

            if (equipoSeleccionado == null) {
                JOptionPane.showMessageDialog(this, "No se pudo determinar el equipo. Seleccione uno válido.");
                return;
            }

            m.setEquipo(equipoSeleccionado);

            // Sincronizar estado seleccionado en cmb_estado con la tabla EquipoOficina
            if (cmb_estado.getSelectedItem() != null) {
                String nuevoEstado = cmb_estado.getSelectedItem().toString();
                equipoSeleccionado.setEstado(nuevoEstado);
                ed.modificarEquipo(equipoSeleccionado);
            }

            String idText = jTextField1.getText().trim();
            if (idText.isEmpty()) {
                boolean ok = mantDao.registrarMantenimiento(m);
                if (ok) {
                    JOptionPane.showMessageDialog(this, "✅ Mantenimiento registrado correctamente.");
                    limpiarFormulario();
                    cargarTablaMantenimientos();
                    cargarComboEquipos(); // recargo combo para reflejar estado actualizado
                    cargarComboPiezas();
                }
            } else {
                try {
                    int id = Integer.parseInt(idText);
                    m.setIdMantenimiento(id);

                    boolean ok = mantDao.modificarMantenimiento(m);
                    if (ok) {
                        JOptionPane.showMessageDialog(this, "✅ Mantenimiento modificado correctamente.");
                        limpiarFormulario();
                        cargarTablaMantenimientos();
                        cargarComboEquipos(); // recargo combo para reflejar estado actualizado
                        cargarComboPiezas();
                    }
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this, "ID inválido.");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }
    }
    public void cargarComboEquipos() {
    cmb_equipos.removeAllItems();
    List<EquipoOficina> lista = ed.listarEquipos();
    System.out.println("DEBUG cargarComboEquipos lista=" + lista);
    if (lista == null || lista.isEmpty()) {
        return;
    }
    for (EquipoOficina e : lista) {
        // añadimos solo el nombre (String) para evitar problemas de tipos
        cmb_equipos.addItem(e.getNombre());
    }
    if (cmb_equipos.getItemCount() > 0) {
        cmb_equipos.setSelectedIndex(0);
    }

}
    public void cargarComboPiezas() {
        cmb_piezas.removeAllItems();
        PiezaInventario sinPieza = new PiezaInventario();
        sinPieza.setIdPieza(0);
        sinPieza.setNombre("Sin repuesto");
        cmb_piezas.addItem(sinPieza);

        for (PiezaInventario pieza : piezaDao.listarPiezas()) {
            cmb_piezas.addItem(pieza);
        }
        if (cmb_piezas.getItemCount() > 0) {
            cmb_piezas.setSelectedIndex(0);
        }
    }

    private void cargarTablaMantenimientos() {
    String col[] = {"id", "Fecha", "Tipo", "Descripcion", "Observaciones", "Equipo", "Estado", "Repuesto usado", "Cant."};
        DefaultTableModel tableModel = new DefaultTableModel(col, 0);
        List<MantenimientoEquipoOficina> lista = mantDao.listarMantenimientos();
        if (lista != null) {
            for (MantenimientoEquipoOficina m : lista) {
                Object[] objs = {
                    m.getIdMantenimiento(),
                    m.getFecha() != null ? m.getFecha().toString() : "",
                    m.getTipo(),
                    m.getDescripcion(),
                    m.getObservaciones(),
                    m.getEquipo() != null ? m.getEquipo().getNombre() : "",
                    m.getEquipo() != null ? m.getEquipo().getEstado() : "",
                    m.getPiezaUsada() != null ? m.getPiezaUsada().getNombre() : "Sin repuesto",
                    m.getCantidadPiezaUsada() > 0 ? m.getCantidadPiezaUsada() : ""
                };
                tableModel.addRow(objs);
            }
        }
        jTable1.setModel(tableModel);
    }//GEN-LAST:event_bt_registrarActionPerformed

    public void limpiarFormulario() {
        if (this.cmb_equipos.getItemCount() > 0) {
            this.cmb_equipos.setSelectedIndex(0);
        }
        this.txt_descripcionman.setText("");
        this.txt_observaciones.setText("");
        this.txt_fechaequipo.setText("");
        this.txt_cantidadpieza.setText("");
        this.jTextField1.setText("");
        this.jTable1.clearSelection();
        this.cmb_tipomanequipo.setSelectedIndex(0);
        if (this.cmb_piezas.getItemCount() > 0) {
            this.cmb_piezas.setSelectedIndex(0);
        }
        
    }

    private void bt_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cerrarActionPerformed

        this.dispose();
    }//GEN-LAST:event_bt_cerrarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = jTable1.getSelectedRow();
        if (fila != -1) {
            Object idObj = jTable1.getValueAt(fila, 0);
            jTextField1.setText(idObj != null ? idObj.toString() : "");

            Object fechaObj = jTable1.getValueAt(fila, 1);
            txt_fechaequipo.setText(fechaObj != null ? fechaObj.toString() : "");

            Object tipoObj = jTable1.getValueAt(fila, 2);
            if (tipoObj != null) {
                cmb_tipomanequipo.setSelectedItem(tipoObj.toString());
            }

            Object descObj = jTable1.getValueAt(fila, 3);
            txt_descripcionman.setText(descObj != null ? descObj.toString() : "");

            Object obsObj = jTable1.getValueAt(fila, 4);
            txt_observaciones.setText(obsObj != null ? obsObj.toString() : "");

            Object equipoObj = jTable1.getValueAt(fila, 5);
            if (equipoObj != null) {
                String nombre = equipoObj.toString();
                for (int i = 0; i < cmb_equipos.getItemCount(); i++) {
                    if (cmb_equipos.getItemAt(i).equals(nombre)) {
                        cmb_equipos.setSelectedIndex(i);
                        break;
                    }
                }
            }

            // sincronizar cmb_estado con el estado del equipo mostrado en la tabla
            Object estadoObj = jTable1.getValueAt(fila, 6);
            if (estadoObj != null) {
                String estado = estadoObj.toString();
                if (estado != null && cmb_estado.getItemCount() > 0) {
                    cmb_estado.setSelectedItem(estado);
                }
            }

            Object piezaObj = jTable1.getColumnCount() > 7 ? jTable1.getValueAt(fila, 7) : null;
            if (piezaObj != null) {
                String nombrePieza = piezaObj.toString();
                for (int i = 0; i < cmb_piezas.getItemCount(); i++) {
                    PiezaInventario pieza = cmb_piezas.getItemAt(i);
                    if (pieza != null && nombrePieza.equals(pieza.getNombre())) {
                        cmb_piezas.setSelectedIndex(i);
                        break;
                    }
                }
            }
            Object cantidadPiezaObj = jTable1.getColumnCount() > 8 ? jTable1.getValueAt(fila, 8) : null;
            txt_cantidadpieza.setText(cantidadPiezaObj != null ? cantidadPiezaObj.toString() : "");

            cambiarAModoEdicion();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed
        if (txt_fechaequipo.getText().trim().isEmpty() ||
        txt_descripcionman.getText().trim().isEmpty() ||
        cmb_tipomanequipo.getSelectedItem() == null ||
        cmb_equipos.getSelectedItem() == null ||
        cmb_estado.getSelectedItem() == null) {
        
        JOptionPane.showMessageDialog(this, "⚠️ Debes completar todos los campos antes de guardar");
        return;
    }
// Verificamos que haya un ID seleccionado
        String idText = jTextField1.getText().trim();
        if (idText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un mantenimiento de la tabla para editar.");
            return;
        }

        try {
            int id = Integer.parseInt(idText);

            MantenimientoEquipoOficina m = new MantenimientoEquipoOficina();
            m.setIdMantenimiento(id);

            if (txt_fechaequipo.getText().trim().isEmpty()) {
                m.setFecha(LocalDate.now());
            } else {
                try {
                    m.setFecha(LocalDate.parse(txt_fechaequipo.getText().trim()));
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Use YYYY-MM-DD.");
                    return;
                }
            }

            m.setTipo(cmb_tipomanequipo.getSelectedItem().toString());
            m.setDescripcion(txt_descripcionman.getText());
            m.setObservaciones(txt_observaciones.getText());

            EquipoOficina equipoSeleccionado = null;
            String nombreSel = (String) cmb_equipos.getSelectedItem();
            List<EquipoOficina> lista = ed.listarEquipos();
            if (lista != null) {
                for (EquipoOficina e : lista) {
                    if (nombreSel.equals(e.getNombre())) {
                        equipoSeleccionado = e;
                        break;
                    }
                }
            }
            if (equipoSeleccionado == null) {
                JOptionPane.showMessageDialog(this, "No se pudo determinar el equipo. Seleccione uno válido.");
                return;
            }

            // sincronizar estado seleccionado en cmb_estado con la tabla EquipoOficina
            if (cmb_estado.getSelectedItem() != null) {
                String nuevoEstado = cmb_estado.getSelectedItem().toString();
                equipoSeleccionado.setEstado(nuevoEstado);
                ed.modificarEquipo(equipoSeleccionado);
            }

            m.setEquipo(equipoSeleccionado);

            boolean ok = mantDao.modificarMantenimiento(m);
            if (ok) {
                JOptionPane.showMessageDialog(this, "✅ Mantenimiento editado correctamente.");
                limpiarFormulario();
                cargarTablaMantenimientos();
                cargarComboEquipos();
                cargarComboPiezas();
            } else {
                JOptionPane.showMessageDialog(this, "❌ No se pudo editar el mantenimiento.");
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "ID inválido.");
        }
    }//GEN-LAST:event_bt_editarActionPerformed

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
        cambiarAModoNuevo();
    }//GEN-LAST:event_bt_cancelarActionPerformed

    private void bt_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarActionPerformed
        if (this.jTextField1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un mantenimiento de la tabla para eliminar.");
            return;
        }
        Integer id_seleccionado = Integer.parseInt(this.jTextField1.getText());
        mantDao.eliminarMantenimiento(id_seleccionado);
        cambiarAModoNuevo();
        cargarTablaMantenimientos();
        this.limpiarFormulario();
        cargarComboEquipos();
        cargarComboPiezas();
    }//GEN-LAST:event_bt_eliminarActionPerformed

    private void cmb_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_estadoActionPerformed

    private void cmb_equiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_equiposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_equiposActionPerformed

    private void bt_refrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_refrescarActionPerformed
    String criterio = txt_buscar.getText().trim();
    if (criterio.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese un ID o Nombre de equipo para buscar.");
        return;
    }

    DefaultTableModel tableModel = new DefaultTableModel(
        new String[]{"id", "Fecha", "Tipo", "Descripcion", "Observaciones", "Equipo", "Estado", "Repuesto usado", "Cant."}, 0);

    try {
        // Si es número -> buscar por ID
        int id = Integer.parseInt(criterio);
        MantenimientoEquipoOficina m = mantDao.buscarPorId(id);
        if (m != null) {
            tableModel.addRow(new Object[]{
                m.getIdMantenimiento(),
                m.getFecha() != null ? m.getFecha().toString() : "",
                m.getTipo(),
                m.getDescripcion(),
                m.getObservaciones(),
                m.getEquipo() != null ? m.getEquipo().getNombre() : "",
                m.getEquipo() != null ? m.getEquipo().getEstado() : "",
                m.getPiezaUsada() != null ? m.getPiezaUsada().getNombre() : "Sin repuesto",
                m.getCantidadPiezaUsada() > 0 ? m.getCantidadPiezaUsada() : ""
            });
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró mantenimiento con ID " + id);
        }
    } catch (NumberFormatException ex) {
        // Si no es número -> buscar por nombre usando listarMantenimientos
        List<MantenimientoEquipoOficina> lista = mantDao.listarMantenimientos();
        int encontrados = 0;
        for (MantenimientoEquipoOficina m : lista) {
            if (m.getEquipo() != null && m.getEquipo().getNombre().equalsIgnoreCase(criterio)) {
                tableModel.addRow(new Object[]{
                    m.getIdMantenimiento(),
                    m.getFecha() != null ? m.getFecha().toString() : "",
                    m.getTipo(),
                    m.getDescripcion(),
                    m.getObservaciones(),
                    m.getEquipo().getNombre(),
                    m.getEquipo().getEstado(),
                    m.getPiezaUsada() != null ? m.getPiezaUsada().getNombre() : "Sin repuesto",
                    m.getCantidadPiezaUsada() > 0 ? m.getCantidadPiezaUsada() : ""
                });
                encontrados++;
            }
        }
        if (encontrados == 0) {
            JOptionPane.showMessageDialog(this, "No se encontró mantenimiento para el equipo con nombre: " + criterio);
        }
    }

    jTable1.setModel(tableModel);
    }//GEN-LAST:event_bt_refrescarActionPerformed
    public void cambiarAModoEdicion() {
        // Habilita botones de edición y deshabilita guardar
        try {
            this.bt_cancelar.setEnabled(true);
        } catch (Exception e) {
        }
        this.bt_eliminar.setEnabled(true);
        this.bt_editar.setEnabled(true);
        this.bt_registrar.setEnabled(false);
    }

    public void cambiarAModoNuevo() {
        // Modo nuevo: habilita guardar, deshabilita editar/eliminar/cancelar y limpia formulario
        try {
            this.bt_cancelar.setEnabled(false);
        } catch (Exception e) {
        }
        this.bt_eliminar.setEnabled(false);
        this.bt_editar.setEnabled(false);
        this.bt_registrar.setEnabled(true);
        limpiarFormulario();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_cerrar;
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_refrescar;
    private javax.swing.JButton bt_registrar;
    private javax.swing.JComboBox<String> cmb_equipos;
    private javax.swing.JComboBox<String> cmb_estado;
    private javax.swing.JComboBox<PiezaInventario> cmb_piezas;
    private javax.swing.JComboBox<String> cmb_tipomanequipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_cantidadpieza;
    private javax.swing.JTextField txt_descripcionman;
    private javax.swing.JTextField txt_fechaequipo;
    private javax.swing.JTextField txt_observaciones;
    // End of variables declaration//GEN-END:variables
}
