/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.transporteshirata.GUI;

import com.mycompany.transporteshirata.Datos.EquipoOficinaDao;
import com.mycompany.transporteshirata.Datos.MantenimientoEquipoDao;
import com.mycompany.transporteshirata.Logica.EquipoOficina;
import com.mycompany.transporteshirata.Logica.MantenimientoEquipoOficina;
import java.awt.event.ActionEvent;
import java.time.LocalDate;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nicolas
 */
public class GuiMantenimientoEquipos extends javax.swing.JInternalFrame {

    EquipoOficinaDao ed = new EquipoOficinaDao();
    MantenimientoEquipoDao mantDao = new MantenimientoEquipoDao();

    /**
     * Creates new form GuiMantenimientoEquipos
     */
    public GuiMantenimientoEquipos() {
        initComponents();
        cargarComboEquipos();          // llena el combo con nombres
        cargarTablaMantenimientos();   // carga la tabla con los mantenimientos
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmb_tipomanequipo = new javax.swing.JComboBox<>();
        cmb_equipos = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        txt_fechaequipo = new javax.swing.JTextField();
        txt_descripcionman = new javax.swing.JTextField();
        txt_observaciones = new javax.swing.JTextField();
        bt_registrar = new javax.swing.JButton();
        bt_cerrar = new javax.swing.JButton();
        bt_editar = new javax.swing.JButton();
        bt_cancelar = new javax.swing.JButton();
        bt_eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel1.setText("ID");

        jLabel2.setText("Fecha");

        jLabel3.setText("Tipo de Mantenimiento");

        jLabel4.setText("Descripcion de Mantenimiento");

        jLabel5.setText("Observaciones");

        jLabel6.setText("Equipo");

        cmb_tipomanequipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Preventivo", "Correctivo" }));

        cmb_equipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        bt_registrar.setText("Guardar");
        bt_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_registrarActionPerformed(evt);
            }
        });

        bt_cerrar.setText("Salir");
        bt_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cerrarActionPerformed(evt);
            }
        });

        bt_editar.setText("Editar");
        bt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarActionPerformed(evt);
            }
        });

        bt_cancelar.setText("Cancelar");
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        bt_eliminar.setText("Eliminar");
        bt_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(151, 151, 151)
                        .addComponent(txt_fechaequipo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_descripcionman)
                                    .addComponent(txt_observaciones)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(bt_registrar)))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bt_editar)
                                    .addComponent(cmb_tipomanequipo, 0, 121, Short.MAX_VALUE)
                                    .addComponent(cmb_equipos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_cerrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_cancelar)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(bt_eliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txt_fechaequipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmb_tipomanequipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_descripcionman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_observaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmb_equipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_registrar)
                    .addComponent(bt_editar))
                .addGap(18, 18, 18)
                .addComponent(bt_eliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_cerrar)
                    .addComponent(bt_cancelar))
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_registrarActionPerformed
        int fila = jTable1.getSelectedRow();

        if (cmb_equipos.getItemCount() == 0 || cmb_equipos.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un equipo en el combo.");
            return;
        }

        try {
            MantenimientoEquipoOficina m = new MantenimientoEquipoOficina();

            // Fecha: si el usuario dejó vacío, uso LocalDate.now(); si escribió, intento parsear YYYY-MM-DD
            if (txt_fechaequipo.getText().trim().isEmpty()) {
                m.setFecha(LocalDate.now());
            } else {
                try {
                    m.setFecha(LocalDate.parse(txt_fechaequipo.getText().trim()));
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Use YYYY-MM-DD.");
                    return;
                }
            }

            m.setTipo(cmb_tipomanequipo.getSelectedItem().toString());
            m.setDescripcion(txt_descripcionman.getText());
            m.setObservaciones(txt_observaciones.getText());

            // Equipo: preferir selección del combo (nombre) y buscar su id
            EquipoOficina equipoSeleccionado = null;
            String nombreSel = (String) cmb_equipos.getSelectedItem();
            if (nombreSel != null) {
                List<EquipoOficina> lista = ed.listarEquipos();
                if (lista != null) {
                    for (EquipoOficina e : lista) {
                        if (nombreSel.equals(e.getNombre())) {
                            equipoSeleccionado = e;
                            break;
                        }
                    }
                }
            }

            if (equipoSeleccionado == null) {
                JOptionPane.showMessageDialog(this, "No se pudo determinar el equipo. Seleccione uno válido.");
                return;
            }

            m.setEquipo(equipoSeleccionado);

            // Si jTextField1 (ID) está vacío -> insertar; si tiene valor -> modificar
            String idText = jTextField1.getText().trim();
            if (idText.isEmpty()) {
                boolean ok = mantDao.registrarMantenimiento(m);
                if (ok) {
                    JOptionPane.showMessageDialog(this, "✅ Mantenimiento registrado correctamente.");
                    limpiarFormulario();
                    cargarTablaMantenimientos();
                }
            } else {
                try {
                    int id = Integer.parseInt(idText);
                    m.setIdMantenimiento(id);
                    boolean ok = mantDao.modificarMantenimiento(m);
                    if (ok) {
                        JOptionPane.showMessageDialog(this, "✅ Mantenimiento modificado correctamente.");
                        limpiarFormulario();
                        cargarTablaMantenimientos();
                    }
                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this, "ID inválido.");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void cargarComboEquipos() {
        cmb_equipos.removeAllItems();
        List<EquipoOficina> lista = ed.listarEquipos();
        if (lista == null) {
            return;
        }
        for (EquipoOficina e : lista) {
            cmb_equipos.addItem(e.getNombre());
        }
        if (cmb_equipos.getItemCount() > 0) {
            cmb_equipos.setSelectedIndex(0);
        }
    }

    private void cargarTablaMantenimientos() {
        String col[] = {"id", "Fecha", "Tipo", "Descripcion", "Observaciones", "Equipo"};
        DefaultTableModel tableModel = new DefaultTableModel(col, 0);
        List<MantenimientoEquipoOficina> lista = mantDao.listarMantenimientos();
        if (lista != null) {
            for (MantenimientoEquipoOficina m : lista) {
                Object[] objs = {
                    m.getIdMantenimiento(),
                    m.getFecha() != null ? m.getFecha().toString() : "",
                    m.getTipo(),
                    m.getDescripcion(),
                    m.getObservaciones(),
                    m.getEquipo() != null ? m.getEquipo().getNombre() : ""
                };
                tableModel.addRow(objs);
            }
        }
        jTable1.setModel(tableModel);
    }//GEN-LAST:event_bt_registrarActionPerformed

    public void limpiarFormulario() {
        if (this.cmb_equipos.getItemCount() > 0) {
            this.cmb_equipos.setSelectedIndex(0);
        }
        this.txt_descripcionman.setText("");
        this.txt_observaciones.setText("");
        this.txt_fechaequipo.setText("");
        this.jTextField1.setText("");
        this.jTable1.clearSelection();
        this.cmb_tipomanequipo.setSelectedIndex(0);
    }

    private void bt_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cerrarActionPerformed

        this.dispose();
    }//GEN-LAST:event_bt_cerrarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = jTable1.getSelectedRow();
        if (fila != -1) {
            // Columnas: 0=id, 1=fecha, 2=tipo, 3=descripcion, 4=observaciones, 5=equipo
            Object idObj = jTable1.getValueAt(fila, 0);
            jTextField1.setText(idObj != null ? idObj.toString() : "");

            Object fechaObj = jTable1.getValueAt(fila, 1);
            txt_fechaequipo.setText(fechaObj != null ? fechaObj.toString() : "");

            Object tipoObj = jTable1.getValueAt(fila, 2);
            if (tipoObj != null) {
                cmb_tipomanequipo.setSelectedItem(tipoObj.toString());
            }

            Object descObj = jTable1.getValueAt(fila, 3);
            txt_descripcionman.setText(descObj != null ? descObj.toString() : "");

            Object obsObj = jTable1.getValueAt(fila, 4);
            txt_observaciones.setText(obsObj != null ? obsObj.toString() : "");

            Object equipoObj = jTable1.getValueAt(fila, 5);
            if (equipoObj != null) {
                String nombre = equipoObj.toString();
                for (int i = 0; i < cmb_equipos.getItemCount(); i++) {
                    if (cmb_equipos.getItemAt(i).equals(nombre)) {
                        cmb_equipos.setSelectedIndex(i);
                        break;
                    }
                }
            }
            cambiarAModoEdicion();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed
        // Verificamos que haya un ID seleccionado
        String idText = jTextField1.getText().trim();
        if (idText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Seleccione un mantenimiento de la tabla para editar.");
            return;
        }

        try {
            int id = Integer.parseInt(idText);

            MantenimientoEquipoOficina m = new MantenimientoEquipoOficina();
            m.setIdMantenimiento(id);

            // Fecha
            if (txt_fechaequipo.getText().trim().isEmpty()) {
                m.setFecha(LocalDate.now());
            } else {
                try {
                    m.setFecha(LocalDate.parse(txt_fechaequipo.getText().trim()));
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Formato de fecha inválido. Use YYYY-MM-DD.");
                    return;
                }
            }

            // Tipo, descripción y observaciones
            m.setTipo(cmb_tipomanequipo.getSelectedItem().toString());
            m.setDescripcion(txt_descripcionman.getText());
            m.setObservaciones(txt_observaciones.getText());

            // Equipo
            EquipoOficina equipoSeleccionado = null;
            String nombreSel = (String) cmb_equipos.getSelectedItem();
            List<EquipoOficina> lista = ed.listarEquipos();
            if (lista != null) {
                for (EquipoOficina e : lista) {
                    if (nombreSel.equals(e.getNombre())) {
                        equipoSeleccionado = e;
                        break;
                    }
                }
            }
            if (equipoSeleccionado == null) {
                JOptionPane.showMessageDialog(this, "No se pudo determinar el equipo. Seleccione uno válido.");
                return;
            }
            m.setEquipo(equipoSeleccionado);

            // Llamada al DAO para modificar
            boolean ok = mantDao.modificarMantenimiento(m);
            if (ok) {
                JOptionPane.showMessageDialog(this, "✅ Mantenimiento editado correctamente.");
                limpiarFormulario();
                cargarTablaMantenimientos();
            } else {
                JOptionPane.showMessageDialog(this, "❌ No se pudo editar el mantenimiento.");
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "ID inválido.");
        }
    }//GEN-LAST:event_bt_editarActionPerformed

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
        cambiarAModoNuevo();
    }//GEN-LAST:event_bt_cancelarActionPerformed

    private void bt_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarActionPerformed
        Integer id_seleccionado = Integer.parseInt(this.jTextField1.getText());
        mantDao.eliminarMantenimiento(id_seleccionado);
        cambiarAModoNuevo();
        cargarTablaMantenimientos();
        this.limpiarFormulario();
    }//GEN-LAST:event_bt_eliminarActionPerformed
    public void cambiarAModoEdicion() {
        // Habilita botones de edición y deshabilita guardar
        try {
            this.bt_cancelar.setEnabled(true);
        } catch (Exception e) {
        }
        this.bt_eliminar.setEnabled(true);
        this.bt_editar.setEnabled(true);
        this.bt_registrar.setEnabled(false);
    }

    public void cambiarAModoNuevo() {
        // Modo nuevo: habilita guardar, deshabilita editar/eliminar/cancelar y limpia formulario
        try {
            this.bt_cancelar.setEnabled(false);
        } catch (Exception e) {
        }
        this.bt_eliminar.setEnabled(false);
        this.bt_editar.setEnabled(false);
        this.bt_registrar.setEnabled(true);
        limpiarFormulario();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_cerrar;
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_registrar;
    private javax.swing.JComboBox<String> cmb_equipos;
    private javax.swing.JComboBox<String> cmb_tipomanequipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txt_descripcionman;
    private javax.swing.JTextField txt_fechaequipo;
    private javax.swing.JTextField txt_observaciones;
    // End of variables declaration//GEN-END:variables
}
