/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.transporteshirata.GUI;

import com.mycompany.transporteshirata.Datos.EquipoOficinaDao;
import com.mycompany.transporteshirata.Datos.SoftwareEquipoDao;
import com.mycompany.transporteshirata.Logica.EquipoOficina;
import com.mycompany.transporteshirata.Logica.SoftwareEquipo;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus
 */
public class GuiSoftwareEquipo extends javax.swing.JInternalFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GuiSoftwareEquipo.class.getName());

    /**
     * Creates new form GuiSoftwareEquipo
     */
    EquipoOficinaDao ed = new EquipoOficinaDao();
    SoftwareEquipoDao swDao = new SoftwareEquipoDao();

    public GuiSoftwareEquipo() {
        initComponents();
        this.setTitle("Gestión de Software de Equipos");
        this.setResizable(true);
        this.setMaximizable(true);
        this.setIconifiable(true);
        this.setSize(950, 550);
        cargarComboEquipos();
        cargarTabla();
        cambiarAModoNuevo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        txt_id_sw = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmb_equipo_sw = new javax.swing.JComboBox<>();
        txt_nombreSoftware_sw = new javax.swing.JTextField();
        txt_version_sw = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_software_sw = new javax.swing.JTable();
        bt_guardar_sw = new javax.swing.JButton();
        bt_actualizar_sw = new javax.swing.JButton();
        bt_eliminar_sw = new javax.swing.JButton();
        bt_cancelar_sw = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_observaciones_sw = new javax.swing.JTextArea();
        txt_fechaActualizacion_sw = new javax.swing.JFormattedTextField();
        txt_fechaInstalacion_sw = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ID");

        txt_id_sw.addActionListener(this::txt_id_swActionPerformed);

        jLabel5.setText("Equipo");

        cmb_equipo_sw.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txt_nombreSoftware_sw.addActionListener(this::txt_nombreSoftware_swActionPerformed);

        txt_version_sw.addActionListener(this::txt_version_swActionPerformed);

        jLabel2.setText("Nombre Software");

        jLabel3.setText("Version ");

        jLabel4.setText("Fecha Actualizacion");

        jLabel6.setText("Fecha Instalacion");

        tbl_software_sw.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_software_sw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_software_swMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_software_sw);

        bt_guardar_sw.setText("Guardar  ");
        bt_guardar_sw.addActionListener(this::bt_guardar_swActionPerformed);

        bt_actualizar_sw.setText("Actualizar Version");
        bt_actualizar_sw.addActionListener(this::bt_actualizar_swActionPerformed);

        bt_eliminar_sw.setText("Eliminar ");
        bt_eliminar_sw.addActionListener(this::bt_eliminar_swActionPerformed);

        bt_cancelar_sw.setText("Cancelar");
        bt_cancelar_sw.addActionListener(this::bt_cancelar_swActionPerformed);

        jLabel7.setText("Observaciones");

        txt_observaciones_sw.setColumns(20);
        txt_observaciones_sw.setRows(5);
        jScrollPane2.setViewportView(txt_observaciones_sw);

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txt_id_sw, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(cmb_equipo_sw, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txt_nombreSoftware_sw, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txt_version_sw, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bt_guardar_sw, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bt_actualizar_sw, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bt_eliminar_sw, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(bt_cancelar_sw, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txt_fechaActualizacion_sw, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txt_fechaInstalacion_sw, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(txt_fechaActualizacion_sw, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_fechaInstalacion_sw, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_nombreSoftware_sw)
                                .addComponent(txt_version_sw)
                                .addComponent(txt_id_sw)
                                .addComponent(cmb_equipo_sw, 0, 115, Short.MAX_VALUE)))
                        .addGap(17, 17, 17)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(bt_guardar_sw)
                                .addGap(18, 18, 18)
                                .addComponent(bt_cancelar_sw)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(bt_eliminar_sw)
                                .addGap(70, 70, 70))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(bt_actualizar_sw)
                                .addGap(40, 40, 40))))))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_cancelar_sw)
                    .addComponent(bt_guardar_sw))
                .addGap(29, 29, 29)
                .addComponent(bt_actualizar_sw)
                .addGap(18, 18, 18)
                .addComponent(bt_eliminar_sw)
                .addGap(59, 59, 59))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_id_sw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmb_equipo_sw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_nombreSoftware_sw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_version_sw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_fechaInstalacion_sw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_fechaActualizacion_sw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>                        

    // ── Validación de fechas ──────────────────────────────────────────────────
    private boolean validarFechas() {
        try {
            java.time.LocalDate fi = java.time.LocalDate.parse(txt_fechaInstalacion_sw.getText().trim());
            java.time.LocalDate fa = java.time.LocalDate.parse(txt_fechaActualizacion_sw.getText().trim());
            if (fa.isBefore(fi)) {
                JOptionPane.showMessageDialog(this,
                        "La fecha de actualización no puede ser anterior a la de instalación.",
                        "Error de fechas", JOptionPane.ERROR_MESSAGE);
                return false;
            }
            return true;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Formato de fecha incorrecto. Usa yyyy-MM-dd (ej: 2024-03-15)",
                    "Error de fechas", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    private void cargarComboEquipos() {
        cmb_equipo_sw.removeAllItems();
        List<EquipoOficina> lista = ed.listarEquipos();
        if (lista == null) {
            return;
        }
        for (EquipoOficina e : lista) {
            cmb_equipo_sw.addItem(e.getNombre());
        }
        if (cmb_equipo_sw.getItemCount() > 0) {
            cmb_equipo_sw.setSelectedIndex(0);
        }
    }

    public void cargarTabla() {
        String[] col = {"ID", "Equipo", "Software", "Version",
            "F. Instalacion", "F. Actualizacion", "Observaciones"};
        DefaultTableModel tableModel = new DefaultTableModel(col, 0) {
            public boolean isCellEditable(int r, int c) {
                return false;
            }
        };
        List<SoftwareEquipo> lista = swDao.listarTodos();
        if (lista != null) {
            for (SoftwareEquipo sw : lista) {
                Object[] objs = {
                    sw.getIdSoftware(),
                    sw.getEquipo() != null ? sw.getEquipo().getNombre() : "",
                    sw.getNombreSoftware(),
                    sw.getVersion(),
                    sw.getFechaInstalacion() != null ? sw.getFechaInstalacion().toString() : "",
                    sw.getFechaActualizacion() != null ? sw.getFechaActualizacion().toString() : "Sin actualizar",
                    sw.getObservaciones() != null ? sw.getObservaciones() : ""
                };
                tableModel.addRow(objs);
            }
        }
        tbl_software_sw.setModel(tableModel);
    }

    private void txt_id_swActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void txt_version_swActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void txt_nombreSoftware_swActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
    }                                                     

    private void tbl_software_swMouseClicked(java.awt.event.MouseEvent evt) {                                             
        int fila = tbl_software_sw.getSelectedRow();
        if (fila == -1) return;

        txt_id_sw.setText(tbl_software_sw.getValueAt(fila, 0).toString());

        Object equipoObj = tbl_software_sw.getValueAt(fila, 1);
        if (equipoObj != null) {
            for (int i = 0; i < cmb_equipo_sw.getItemCount(); i++) {
                if (cmb_equipo_sw.getItemAt(i).equals(equipoObj.toString())) {
                    cmb_equipo_sw.setSelectedIndex(i);
                    break;
                }
            }
        }
        
        txt_nombreSoftware_sw.setText(tbl_software_sw.getValueAt(fila, 2).toString());
        txt_version_sw.setText(tbl_software_sw.getValueAt(fila, 3).toString());
        
        
        // columna 4 = F. Instalacion, columna 5 = F. Actualizacion
        Object fi = tbl_software_sw.getValueAt(fila, 4);
        txt_fechaInstalacion_sw.setText(fi != null ? fi.toString() : "");

        Object fa = tbl_software_sw.getValueAt(fila, 5);
        txt_fechaActualizacion_sw.setText(
            fa != null && !fa.toString().equals("Sin actualizar") ? fa.toString() : "");

        Object obs = tbl_software_sw.getValueAt(fila, 6);
        txt_observaciones_sw.setText(obs != null ? obs.toString() : "");

        cambiarAModoEdicion();
        // TODO add your handling code here:
    }                                            

    private void bt_guardar_swActionPerformed(java.awt.event.ActionEvent evt) {                                              
        if (cmb_equipo_sw.getItemCount() == 0 || cmb_equipo_sw.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un equipo.");
            return;
        }
        if (txt_nombreSoftware_sw.getText().trim().isEmpty() || txt_version_sw.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre del software y la version son obligatorios.");
            return;
        }
        if (!validarFechas()) return;

        String nombreSel = (String) cmb_equipo_sw.getSelectedItem();
        EquipoOficina equipoSeleccionado = null;
        for (EquipoOficina e : ed.listarEquipos()) {
            if (nombreSel.equals(e.getNombre())) {
                equipoSeleccionado = e;
                break;
            }
        }
        if (equipoSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "No se pudo identificar el equipo seleccionado.");
            return;
        }

        SoftwareEquipo sw = new SoftwareEquipo();
        sw.setEquipo(equipoSeleccionado);
        sw.setNombreSoftware(txt_nombreSoftware_sw.getText().trim());
        sw.setVersion(txt_version_sw.getText().trim());
        sw.setFechaInstalacion(java.time.LocalDate.parse(txt_fechaInstalacion_sw.getText().trim()));
        sw.setFechaActualizacion(java.time.LocalDate.parse(txt_fechaActualizacion_sw.getText().trim()));
        sw.setObservaciones(txt_observaciones_sw.getText().trim());

        if (swDao.registrarSoftware(sw)) {
            JOptionPane.showMessageDialog(this, "Software guardado exitosamente.");
            cargarTabla();
            limpiarFormulario();
            cambiarAModoNuevo();
        }
        // TODO add your handling code here:
    }                                             

    private void bt_actualizar_swActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        if (txt_id_sw.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecciona un software de la tabla.");
            return;
        }
        if (txt_version_sw.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingresa la nueva version.");
            return;
        }
        if (!validarFechas()) return;

        SoftwareEquipo sw = new SoftwareEquipo();
        sw.setIdSoftware(Integer.parseInt(txt_id_sw.getText().trim()));
        sw.setVersion(txt_version_sw.getText().trim());
        sw.setFechaActualizacion(java.time.LocalDate.parse(txt_fechaActualizacion_sw.getText().trim()));
        sw.setObservaciones(txt_observaciones_sw.getText().trim());

        if (swDao.actualizarVersion(sw)) {
            JOptionPane.showMessageDialog(this,
                "Version actualizada correctamente.\n"
                + "Software: " + txt_nombreSoftware_sw.getText() + "\n"
                + "Nueva version: " + sw.getVersion() + "\n"
                + "Fecha: " + sw.getFechaActualizacion());
            cargarTabla();
            limpiarFormulario();
            cambiarAModoNuevo();
        }
        // TODO add your handling code here:
    }                                                

    private void bt_eliminar_swActionPerformed(java.awt.event.ActionEvent evt) {                                               
        if (txt_id_sw.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecciona un software de la tabla.");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this,
            "¿Eliminar el registro de \"" + txt_nombreSoftware_sw.getText() + "\"?",
            "Confirmar eliminacion", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            swDao.eliminarSoftware(Integer.parseInt(txt_id_sw.getText().trim()));
            JOptionPane.showMessageDialog(this, "Software eliminado.");
            cargarTabla();
            limpiarFormulario();
            cambiarAModoNuevo();
        }
        // TODO add your handling code here:
    }                                              

    private void bt_cancelar_swActionPerformed(java.awt.event.ActionEvent evt) {                                               
        limpiarFormulario();
        cambiarAModoNuevo();
        // TODO add your handling code here:
    }                                              

    public void limpiarFormulario() {
        txt_id_sw.setText("");
        txt_nombreSoftware_sw.setText("");
        txt_version_sw.setText("");
        txt_fechaInstalacion_sw.setText(java.time.LocalDate.now().toString());
        txt_fechaActualizacion_sw.setText(java.time.LocalDate.now().toString());
        txt_observaciones_sw.setText("");
        if (cmb_equipo_sw.getItemCount() > 0) cmb_equipo_sw.setSelectedIndex(0);
        tbl_software_sw.clearSelection();
    }

    public void cambiarAModoNuevo() {
        bt_guardar_sw.setEnabled(true);
        bt_actualizar_sw.setEnabled(false);
        bt_eliminar_sw.setEnabled(false);
        bt_cancelar_sw.setEnabled(false);
    }

    public void cambiarAModoEdicion() {
        bt_guardar_sw.setEnabled(false);
        bt_actualizar_sw.setEnabled(true);
        bt_eliminar_sw.setEnabled(true);
        bt_cancelar_sw.setEnabled(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GuiSoftwareEquipo().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton bt_actualizar_sw;
    private javax.swing.JButton bt_cancelar_sw;
    private javax.swing.JButton bt_eliminar_sw;
    private javax.swing.JButton bt_guardar_sw;
    private javax.swing.JComboBox<String> cmb_equipo_sw;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_software_sw;
    private javax.swing.JFormattedTextField txt_fechaActualizacion_sw;
    private javax.swing.JFormattedTextField txt_fechaInstalacion_sw;
    private javax.swing.JTextField txt_id_sw;
    private javax.swing.JTextField txt_nombreSoftware_sw;
    private javax.swing.JTextArea txt_observaciones_sw;
    private javax.swing.JTextField txt_version_sw;
    // End of variables declaration                   
}
